local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.g.alchemy.com/v2/u28p93Y4wW9jIqF_3Tdbc

maturity-ladder:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.g.alchemy.com/v2/u28p93Y4wW9jIqF_3Tdbc

asset-quality:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.g.alchemy.com/v2/u28p93Y4wW9jIqF_3Tdbc

compliance-drift:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.g.alchemy.com/v2/u28p93Y4wW9jIqF_3Tdbc

concentration-drift:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.g.alchemy.com/v2/u28p93Y4wW9jIqF_3Tdbc

early-warning:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.g.alchemy.com/v2/u28p93Y4wW9jIqF_3Tdbc

approach3:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.g.alchemy.com/v2/u28p93Y4wW9jIqF_3Tdbc

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://eth-sepolia.g.alchemy.com/v2/u28p93Y4wW9jIqF_3Tdbc
